// Dependencies: mongoose and Schema are used to create the model; moment is used to create a pre-formatted date for each workout
const mongoose = require("mongoose");
const moment = require('moment');
const Schema = mongoose.Schema;

const workoutSchema = new Schema({

  // Exercises are stored in an array since each workout can have multiple exercises
  exercises: [ {
    _id: false, // Prevents an ID from automatically being generated by Mongoose for the array
    type: {
      type: String,
      trim: true
    },
    name: {
      type: String,
      trim: true,
    },
    duration: {
      type: Number,
    },
    distance: {
      type: Number,
      default: 0
    },
    weight: {
      type: Number,
      default: 0
    },
    sets: {
      type: Number,
      default: 0
    },
    reps: {
      type: Number,
      default: 0
    },
  } ],
  date: {
    type: Date,
    default: Date.now
  },

  // Formats a date to the following format: May 21st 2021
  formatted_date: {
    type: String,
    default: moment().format('MMMM Do YYYY')
  }
});

const Workout = mongoose.model("Workout", workoutSchema);

module.exports = Workout;